apiVersion: v1
kind: Service
metadata:
  name: k8s-frontend
spec:
  type: NodePort
  selector:
    app: k8s-frontend
  ports:
    - port: 80           # Service port inside cluster
      targetPort: 80     # Container port (Nginx)
      nodePort: 30000    # External port on Minikube node

