apiVersion: v1
kind: Service
metadata:
  name: k8s-frontend
spec:
  type: LoadBalancer
  selector:
    app: k8s-frontend
  ports:
    - port: 80           # Service port inside cluster
      targetPort: 80     # Container port (Nginx)


