apiVersion: v1
kind: Service
metadata:
  name: k8s-server
spec:
  type: LoadBalancer
  selector:
    app: k8s-server
  ports:
  - name: k8s-server
    protocol: TCP
    port: 3001
    targetPort: 3001
