apiVersion: v1
kind: Service
metadata:
  name: ceramicraft-auth-service
  namespace: ceramicraft
spec:
  selector:
    app: ceramicraft-auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
